package barber;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ace
 */
import java.sql.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.EditorKit;
import javax.swing.text.html.HTMLEditorKit;
import java.sql.*;
import com.mysql.jdbc.Driver;

public class cetak_transaksi extends javax.swing.JFrame {
    Connection sambungan;
    
    /**
     * Creates new form cetak_transaksi
     */
    
    
    public cetak_transaksi() {
        initComponents();
        sambung();
        cetak();
    }
    
    private void sambung() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Sukses Driver JDBC ditemukan..");
            try {
                String url = "jdbc:mysql://localhost/barbershop?user=root&password=daniel";
                sambungan = DriverManager.getConnection(url);
                System.out.println("Sukses koneksi ");
            }catch (SQLException se){
                System.out.println("GAGAL koneksi = "+ se);
                System.exit(0);
            }
        }catch (ClassNotFoundException cnfe){
            JOptionPane.showMessageDialog(null, "Class Tidak Ditemukan.. Error : "+cnfe);
            System.exit(0);
        }
    }
    
    public void cetak(){
    String html =
            "<H1> <center> DaSaR Barbershop </center></H1> "
            +"<H2> <center> JL. Jalan Bapakmu !!</center></H2>"
            +"---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
            +"<BR>LAPORAN TRANSAKSI</BR>"
            +"<BR></BR>"
            +"<BR></BR>"
            +"<table width='100%' border='0'  cellpadding='5' cellspacing='1'>"+
            "<tr>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>KODE TRANSAKSI</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>KODE ORDER</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>ID PEGAWAI</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>ID KARYAWAN</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>TANGGAL TRANSAKSI</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>TOTAL BAYAR</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>BAYAR</strong></td>"
                +"<td bgcolor='#CCCCCC' align='center'><strong>KEMBALI</strong></td>"
                +"</tr>";
    try{
        sambung();
        String sql = "Select *from transaksi1";
        PreparedStatement stat = (PreparedStatement) sambungan.prepareStatement(sql);
        ResultSet set = stat.executeQuery(sql);
        while(set.next()){
        html = html + "<tr>"
                + "<td bgcolor='#EEEEEE'>"+set.getString("kode_transaksi")+"</td>"
                +" <td bgcolor='#F8F8F8'>"+set.getString("kode_order")+"</td>"
                +" <td bgcolor='#F8F8F8'>"+set.getString("id_pelanggan")+"</td>"
                + "<td bgcolor='#EEEEEE'>"+set.getString("id_karyawan")+"</td>"
                +" <td bgcolor='#F8F8F8'>"+set.getString("tgl_transaksi")+"</td>"
                + "<td bgcolor='#EEEEEE'>"+set.getString("total_bayar")+"</td>"
                + "<td bgcolor='#EEEEEE'>"+set.getString("bayar")+"</td>"
                + "<td bgcolor='#EEEEEE'>"+set.getString("kembali")+"</td>"
                +"</tr>";
        }
        EditorKit x = new HTMLEditorKit();
        jEditorPane2.setEditorKit(x);
        jEditorPane2.setText(html);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        print = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane2.setViewportView(jEditorPane2);

        jScrollPane1.setViewportView(jScrollPane2);

        print.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        print.setText("PRINT");
        print.setToolTipText("Cetak Data");
        print.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        kembali.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kembali.setText("CLOSE");
        kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
            boolean complete = jEditorPane2.print();
            if (complete){
                JOptionPane.showMessageDialog(null, "Berhasil");
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal!!");
            }
        }catch (PrinterException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        int tanya = JOptionPane.showConfirmDialog(null, "Ingin kembali ke form ? ", "tanya",JOptionPane.YES_NO_CANCEL_OPTION);
        if(tanya==0){
            new laporanTransaksi().setVisible(true);
            this.dispose();
        }else {
            this.dispose();
        }
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetak_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetak_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetak_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetak_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetak_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
