/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barber;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author hp
 */
public class menuUtama extends javax.swing.JFrame {
    
    public menuUtama() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        new Thread(){
            public void run(){
            while (true) {
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);
                int bulan = kal.get(Calendar.MONTH)+1;
                int hari = kal.get(Calendar.DAY_OF_MONTH);
                String tanggal = tahun+"-"+bulan+"-"+hari;
                TanggalSekarang.setText(tanggal);
            }
        }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        m_Utama = new javax.swing.JLabel();
        m_Layanan = new javax.swing.JLabel();
        m_Transaksi = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        m_pelanggan = new javax.swing.JLabel();
        m_Karyawan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TanggalSekarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DaSaR BarberShop");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 490, 90));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        m_Utama.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        m_Utama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_Utama.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\salon.png")); // NOI18N
        m_Utama.setToolTipText("MENU");
        m_Utama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_Utama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_Utama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_Utama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_UtamaMouseClicked(evt);
            }
        });

        m_Layanan.setBackground(new java.awt.Color(153, 153, 153));
        m_Layanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_Layanan.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\customer.png")); // NOI18N
        m_Layanan.setToolTipText("Daftar Layanan");
        m_Layanan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_Layanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_Layanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_Layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_LayananMouseClicked(evt);
            }
        });

        m_Transaksi.setBackground(new java.awt.Color(153, 153, 153));
        m_Transaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_Transaksi.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\write-letter.png")); // NOI18N
        m_Transaksi.setToolTipText("Transaksi");
        m_Transaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_Transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_Transaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_TransaksiMouseClicked(evt);
            }
        });

        keluar.setBackground(new java.awt.Color(153, 153, 153));
        keluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keluar.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\power.png")); // NOI18N
        keluar.setToolTipText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        m_pelanggan.setBackground(new java.awt.Color(153, 153, 153));
        m_pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_pelanggan.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\barber.png")); // NOI18N
        m_pelanggan.setToolTipText("Let's Work !..");
        m_pelanggan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_pelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pelangganMouseClicked(evt);
            }
        });

        m_Karyawan.setBackground(new java.awt.Color(153, 153, 153));
        m_Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m_Karyawan.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\Menu\\workers.png")); // NOI18N
        m_Karyawan.setToolTipText("Karyawan");
        m_Karyawan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_Karyawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_Karyawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_KaryawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(m_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(m_Layanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(m_Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(m_Utama, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_Layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO DASAR BARBERSHOP.");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("SUDAH SIAPKAN MEMBERIKAN SENYUMAN DAN STYLE ISTIMEWA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("UNTUK DUNIA HARI INI ?");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LETS WORK TEAM..");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 910, 420));
        jPanel1.add(TanggalSekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Daniel\\ICON\\barber\\background cut3.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_keluarMouseClicked

    private void m_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pelangganMouseClicked
        // TODO add your handling code here:
        new menuPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_pelangganMouseClicked

    private void m_KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_KaryawanMouseClicked
        // TODO add your handling code here:
        new menuKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_KaryawanMouseClicked

    private void m_LayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_LayananMouseClicked
        // TODO add your handling code here:
        new menuLayanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_LayananMouseClicked

    private void m_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_TransaksiMouseClicked
        // TODO add your handling code here:
        new menuTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_TransaksiMouseClicked

    private void m_UtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_UtamaMouseClicked
        // TODO add your handling code here:
        new menuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_UtamaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TanggalSekarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel m_Karyawan;
    private javax.swing.JLabel m_Layanan;
    private javax.swing.JLabel m_Transaksi;
    private javax.swing.JLabel m_Utama;
    private javax.swing.JLabel m_pelanggan;
    // End of variables declaration//GEN-END:variables
}
